version: '3.9'
services:
  blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: my-blog
    ports:
      - '4321:4321'
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
volumes:
  node_modules: